### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by aamirkhan2478** [Recillah-Khamala/Leaderboard-Project#2]
# Morning Session: Peer-to-Peer Coding Review.
Good job working on this project so far. 💪 👏 👏 .

The project looks promising.
- Good job on the design. This makes the project truly yours.
- Good use of modules(You created many module files).
- Optional changes.

Kindly consider making the below suggestions.
- Update README.md with your correct live URL.
- When you use async await you should not use the `.then` method. 
- kindly make your project more modular, by separating functionalities. For example, it is better to create separate functions for rendering data to the UI, fetching data from API, posting data to the API and many more. This will make your code more readable and scalable.

**Comment by Recillah-Khamala** [comment]
Done
